### ISSUE TITLE
time stamps are weird

### ISSUE THREAD

**Issue by mariaf3s** [vahid-sb/LSL_Video_Acquisition#1]
Hello, I was able to implement this code I was able to get a video file to output as well as an xdf file from LSL, but the issue I am having is the video starts recording as soon as I run the python script, and I want it to start recording when I start from lab recorder, also, this would be fine if I could some how sync the time for the two, but I cant figure out how to do that. Any suggestions?

**Comment by vahid-sb** [comment]
Hi @mariaf3s 
1. The relationship between LSL inlets, such as this script, and LSL Lab Recorder is unidirectional. It means the Lab Recorder cannot send a signal to a script or an app to start or stop them. THence, this is not an issue that has a solution, becasue of how the Lab Recorder is designed. So, what I can suggest is to start the video acquisition not long before recording in Lab recorder starts, so you won't end up with a huge video file.
2. When you stop the Lab recorder (and the Video Acquisitoin) you will see in the relevant stream in the xdf file, a time_series of frame numbers. If one million frames are saved into the video file before Lab recorder starts, the frame numbers in xdf stream start from one million and one. And then you have a time_stamp for each frame. But if you want to have the time stamp relative to the begining of the video and not the frame number, you can simply divide the frame number over the video frame-rate.
Hope that helped.

**Comment by mariaf3s** [comment]
Thank you so much for this! I see now how it works. Very Appreciative!
